Create CONTRIBUTING.md
IntersectMBO/OSC-documentation pull request #10
Opened 2024-06-04 16:40 UTC by Ranchhand87

Add any additional desired specificities.

2024-06-11 01:32 UTC, Ranchhand87 commented
@Ryun1 Can you compare this to the template. Let me know if I need to redo. Thanks

2024-06-11 07:56 UTC, Ryun1 commented on CONTRIBUTING.md
> +# Contributing to [OSC-documentation]
```suggestion
# Contributing to OSC-documentation
```

I would remove the `[ ]` because they would make it look like a hyperlink

2024-06-11 07:57 UTC, Ryun1 commented on CONTRIBUTING.md
> +## Types of contribution
```suggestion

## Types of contribution

```
spaces between headers are good practice with markdown files

2024-06-11 07:59 UTC, Ryun1 commented on CONTRIBUTING.md
> +The Code of Conduct governs this project and everyone participating. By participating, you are expected to uphold this code. Please report unacceptable behavior to [email].
```suggestion
[The Code of Conduct](https://github.com/IntersectMBO/OSC-documentation/blob/master/CODE-OF-CONDUCT.md) governs this project and everyone participating. By participating, you are expected to uphold this code. Please report unacceptable behavior to [oso@intersectmbo.org](https://github.com/IntersectMBO/committee-documentation-template/blob/main/oso@intersectmbo.org).
```

add link to code of conduct and oso email

2024-06-11 08:00 UTC, Ryun1 commented on CONTRIBUTING.md
> +If you are subject to or witness unacceptable behavior or have any other concerns, please notify a community organizer as soon as possible.
this doesnt really make sense under Reporting Bugs - maybe a copy paste error?

2024-06-11 08:01 UTC, Ryun1 commented on CONTRIBUTING.md
> +Need help determining where to begin contributing to [Project Name]? You can start by looking through these `beginner` and `help-wanted` issues:
```suggestion
Need help determining where to begin contributing to [OSC Documentation](https://github.com/IntersectMBO/OSC-documentation)? You can start by looking through these `beginner` and `help-wanted` issues:
```

2024-06-11 08:01 UTC, Ryun1 commented on CONTRIBUTING.md
> +All [Haskell] must adhere to [Haskell] Standard Style.
```suggestion
```
can probably remove, as this repo wont have any haskell

2024-06-11 08:02 UTC, Ryun1 commented on CONTRIBUTING.md
> +Use Markdown for documentation.
```suggestion
Use Markdown for documentation.
Following [best practices](https://www.markdownguide.org/basic-syntax/).
```

2024-06-11 08:03 UTC, Ryun1 approved these changes

2024-06-11 08:04 UTC, Ryun1 requested changes
added a few comments, in general this is fine but [the template](https://github.com/IntersectMBO/committee-documentation-template/blob/main/CONTRIBUTING.md) does have more content you could copy in.

2024-06-17 23:40 UTC, Ranchhand87 reviewed
@ThatGuyLLC please push.

2024-06-17 23:40 UTC, merged